files:
  - source: '/[a-c]*/**/*.properties'
    ignore:
      - /**/*_*.properties
      - /**/velocity.properties
      - /**/log4j.properties
    translation: /**/%file_name%_%locale_with_underscore%.%file_extension%
